const assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm');
const html=fs.readFileSync('index.html','utf8');
const metadata=JSON.parse(fs.readFileSync('metadata/problem-dna.json','utf8'));
const ctx={problemDna:metadata,esc:s=>String(s),CBY:{},selected:[]};
vm.createContext(ctx);vm.runInContext(html.slice(html.indexOf('const CONCEPTS ='),html.indexOf('function relatedCard(')),ctx);
const from=(uid)=>({uid,country:uid.split('.')[0],text:metadata.records[uid].reviewed_statement});
const source=from('nz.2020.0.2'), harder=from('nz.2024.0.4');
assert.ok(ctx.reviewedDna(source));
assert.equal(ctx.reviewedDna({...source,text:'Changed'}),null);
assert.match(ctx.dnaHtml(source),/Problem DNA — reveal techniques/);
assert.doesNotMatch(ctx.dnaHtml({...source,text:'Changed'}),/reveal techniques/);
const similar={uid:'xx.2020.0.1',country:'xx',text:'Find all primes satisfying the following congruences and remainders.'};
const results=ctx.relatedProblems(source,[source,{...source,uid:'xx.2020.0.2'},harder,similar,{uid:'xx.2020.0.3',text:'A triangle ABC has circumcircle.'}]);
assert.equal(results.length,2);assert.ok(results.some(x=>x.problem.uid===harder.uid));
assert.ok(results.every(x=>x.shared.length>=2 || x.methods.length));
const methods=ctx.relatedProblems(from('au.2016.1.1'),[harder]);
assert.deepEqual(Array.from(methods[0].methods),['modular-arithmetic']);
assert.ok(methods[0].dna.practice_level>metadata.records['au.2016.1.1'].practice_level);
const noMatch=ctx.relatedProblems(source,[{uid:'xx.2020.0.4',text:'Find a triangle.'}]);assert.equal(noMatch.length,0);
console.log('Connections checks passed: reviewed DNA, stale snapshots, self/duplicate exclusion, shared methods and unrelated filtering.');
